apiVersion: v1
kind: Service
metadata:
  name: hello-zero-aspnetcore-service
spec:
  selector:
    app: hello-zero-aspnetcore-pod
  ports:
  - port: 8080
    targetPort: 80
  type: LoadBalancer